### PR TITLE
Add Cypress record key

### PR DESCRIPTION
**Pull request by nikitastupin**
Hi team,

Adding information on how to check Cypress record key 😃 

Thanks for the project!

### CODE REVIEW

**Review by yezz123 — COMMENTED** [review]
what about a key for Applitools ?

**Review by streaak — CHANGES_REQUESTED** [review]
Could you remove the Key and project id and use a specific keyword instead? Thank you

**Comment by nikitastupin** [comment]
Hi @streaak ,

I've just replaced projectId and recordKey values with placeholders!

**Review by codingo — APPROVED** [review]

**Comment by codingo** [comment]
@nikitastupin this has become a bit of a dirty merge due to later changes, do you want to take first crack at resolving the conflicts?

**Comment by nikitastupin** [comment]
@codingo done

**Comment by streaak** [comment]
Thanks @nikitastupin

**Pull request merged**
