### PR TITLE
PR for a few new API keys and Issues

### PR DESCRIPTION
**Pull request by knadt**
Please see commit descriptions for fixes and updates

### CODE REVIEW

**Comment by knadt** [comment]
https://github.com/streaak/keyhacks/issues/85 - AMPLITUDE API Keys added
https://github.com/streaak/keyhacks/issues/77 - added more v1 endpoints and one v2 endpoint

**Comment by streaak** [comment]
Give me a few days to look into this.

**Comment by knadt** [comment]
yeah sure no problem

**Comment by knadt** [comment]
Hey @streaak, I hope you are well. any feedback?

**Comment by streaak** [comment]
Hey @knadt 
Sorry, Been swamped with work and uni, haven't had time to look at this.

**Pull request merged**
